name: Actualizar README con últimos proyectos

on:
  schedule:
    - cron: '0 0 * * *'  # Se ejecutará todos los días a medianoche (UTC)
  workflow_dispatch:  # Para que también puedas ejecutarlo manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar dependencias
      run: npm install node-fetch

    - name: Ejecutar script para actualizar README
      run: node update-readme.js

    - name: Commit y push cambios
      run: |
        git config --global user.name 'Jose Familia'
        git config --global user.email 'familiajoserene@gmail.com'
        git add README.md
        git commit -m 'Actualizar README con los últimos proyectos'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
