 name: WakaTime Update
 on:
   schedule:
     - cron: '0 0 * * *' # Runs at midnight every day
   workflow_dispatch:
 jobs:
   update-readme:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: waka-box
         uses: matchai/waka-box@v5.0.0
         env:
           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
