name: Update Wakatime Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch Wakatime stats
      uses: jsmrcaga/action-wakatime-stats@v1.0.0
      with:
        wakatime-api-key: ${{ secrets.WAKATIME_API_KEY }}
        output_file: STATS.md  # Temporary stats file
    - name: Update README
      run: |
        sed -i '/<!-- wakatime-stats-start -->/,/<!-- wakatime-stats-end -->/{
            /<!-- wakatime-stats-start -->/!d; x; s/.*//; x;
            /<!-- wakatime-stats-end -->/!d; G
        }' README.md
        cat STATS.md >> README.md
    - name: Commit and push
      uses: EndBug/add-and-commit@v7
      with:
        message: 'Updated Wakatime statistics'
        add: 'README.md'
