name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Ejecutar cada domingo a la medianoche (UTC)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install node-fetch dotenv

    - name: Update README
      run: node scripts/update-readme.cjs
      env:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        WAKATIME_USER_ID: ${{ secrets.WAKATIME_USER_ID }}

